name: pr

on:
  pull_request:

# Automate repetetive processes by returning visual feedback for testing & linting to the reviewers

jobs:
    cypress-run:
      runs-on: ubuntu-16.04
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Cypress run
          uses: cypress-io/github-action@v2
          with:
            build: npm run build
            start: npm run start
            wait-on: http://localhost:3000
